### PR TITLE
fixes #99, no xmlMode

### LINKED ISSUE #99: Formatting issues
We're running library on Heroku, and recently upgraded from https://github.com/nytimes/library/commit/a4f9e4255c0a6e48df8b7a5e92f128256b408280 to the latest master https://github.com/nytimes/library/commit/5015b9e7050e990bf70aa1864078674b9d5fed09.

There is only one significant change in this diff: https://github.com/nytimes/library/pull/92

Since upgrading it seems some of the formatter logic that strips out superfluous html tags is broken, though I'm not familiar enough with the code base to pinpoint it exactly.

Specifically, we are seeing `<a>` tags that don't belong in the body:

<table><tr><td>
Screenshot 2020-03-06 at 20 40 51
</td></tr></table>

The relevant HTML looks like this:

Screenshot 2020-03-06 at 20 41 21

Downgrading restores the expected behavior:

<table><tr><td>
Screenshot 2020-03-06 at 20 44 44
</td></tr></table>

Screenshot 2020-03-06 at 20 42 08

Please also note the difference in spacing between paragraphs. It seems #92 changes behavior and doesn't include empty `<p>`s between paragraphs any more.

Please let me know if there's any way we can help in diagnosing this issue. Thank you for building and open sourcing this amazing project.

### PR DESCRIPTION
**Pull request by isaacwhite**
Looks like #92 switch to `xmlMode` introduced some self closing `a` tags, which Chrome is failing to recognize. This PR disables `xmlMode` and addresses the intent of that switch by returning the `head` and `body` HTML instead of the entirety of the cheerio virtual `$.html()`.

### Related Issue
Closes #99 

### Checklist

- [x] Ran `npm run lint` and updated code style accordingly
- [x] `npm run test` passes
- [x] PR has a description and all contributors/stakeholder are noted/cc'ed
- ~[ ] tests are updated and/or added to cover new code~
- ~[ ] relevant documentation is changed and/or added~

### CODE REVIEW

File: server/formatter.js [hunk 1]
```diff
@@ -170,7 +170,7 @@ function fetchByline(html, creatorOfDoc) {
   })
 
   return {
-    html: $.html(),
+    html: $('head').html() + $('body').html(), // include head for list style block
```
Comment (afischer) [inline server/formatter.js]: 👍
