### PR TITLE
Formatter Fixes

### LINKED ISSUE #34: EJS template string in Google Docs are not escaped correctly when rendering
### Expected Behavior
In Google Doc:
````
```
<%- include('./../default/partials/pagination', { pages }) %>
```
````

The code snippet should render with the contents:
> 1. <%- include('./../default/partials/pagination', { pages }) %>

### Actual Behavior
The code snippet is rendered empty:
> 1. 

### Possible Solution

Is there a conflict between the EJS templating and EJS template strings?

### LINKED ISSUE #44: Document titles ending in `home` are interpreted as homepages when not tagged
### Expected Behavior
The word "home" should be preserved at the end of a document name and not used as a tag unless it follows a `|` character.

### Actual Behavior
`home` is stripped from the end of document titles and the document becomes the homepage for the folder it is in

### To Reproduce
See: https://nyt-library-demo.herokuapp.com/semi-secret/deeply-nested-folder

### Possible Solution
Update the tags regex and investigate homepage selection logic

### PR DESCRIPTION
**Pull request by afischer**
### Description of Change
Some small formatter fixes around tags and inline code, as well as some additional tests.
- Fixes an issue where "home" would be stripped from the end of document titles in page names
- Fixes an issue where ejs template strings in code blocks would be deleted if `ALLOW_INLINE_CODE` was enabled
- Adjusts the logic to parse and unescape inline code blocks.

### Related Issue
Fixes #44
Fixes #34

### Checklist

- [x] Ran `npm run lint` and updated code style accordingly
- [x] `npm run test` passes
- [x] PR has a description and all contributors/stakeholder are noted/cc'ed
- [x] tests are updated and/or added to cover new code
- [x] relevant documentation is changed and/or added

### CODE REVIEW

File: server/formatter.js [hunk 1]
```diff
@@ -113,11 +113,22 @@ function formatCode(html) {
...
-    const html = unescape(content)
-    return formatCodeContent(html)
-  })
+  // for inline code option
+  if (allowInlineCode) {
+    const matches = []
+    // get all code matches, push any that are not <pre> wrapped
+    html.replace(/&lt;%-.*?\s?%&gt;(.*?<\/pre>)?/g, (codeContent, closingPre) => {
+      if (!closingPre) matches.push(codeContent)
+    })
```
Comment (afischer) [inline server/formatter.js]: I'm sure there is a better way to do this with something like `.filter` instead of abusing the replace callback, but need to think on it a bit more...

File: test/unit/htmlProcessing.test.js [hunk 2]
```diff
@@ -87,6 +90,51 @@ describe('HTML processing', () => {
...
+        assert.equal(styleTag.html(), '&lt;style&gt;')
+        assert.equal(openingTag.html(), '&lt;%-')
+      })
+    })
+
+    describe('with inline code enabled', () => {
+      before(function () {
+        process.env.ALLOW_INLINE_CODE = 'true'
+        // remove formatter from require cache to recognize changed env variable
+        delete require.cache[require.resolve(formatterPath)]
```
Comment (afischer) [inline test/unit/htmlProcessing.test.js]: Not a fan of this and considered modifying the formatter functions to take `allowInlineCode` as an argument that defaults to the environment variable, but it seems like not a great idea to modify code to better fit our testing suite than to run the code as it would be in a production-like way...

File: server/formatter.js (hunk 1 above)
Comment (isaacwhite) [reply server/formatter.js]: Hey @afischer, I'm OK with this for now but want to circle back to see if you had any updated thoughts on how to handle this.

Comment (afischer) [reply server/formatter.js]: Sure — I’m not sure there’s a super elegant way to do so while continuing to support Node 8, but I can definite dig in a bit more
